name: Run release tests

on:
  workflow_dispatch:


env:
  # env vars that are secrets should always be set in the env field, so they aren't visible in $GITHUB_ENV file
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  RESULTS_LOCATION: ${{ secrets.RESULTS_LOCATION }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

jobs:
  run_release_tests:
    name: run release tests
    runs-on:
      group: aws-athena-query-federation
    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get install -y libxml2-utils python3
          pip3 install lxml beautifulsoup4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
            java-version: '11'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build jars
        run: mvn clean package -T 1C -DskipTests
      
      - name: Set dynamic env vars
        run: |
          echo "REPOSITORY_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "VALIDATION_TESTING_ROOT=$REPOSITORY_ROOT/validation_testing" >> $GITHUB_ENV
      # now our environment is fully prepared, we can run our test script
      - name: Run tests
        run: cd $VALIDATION_TESTING_ROOT && python3 main.py

